version: "3.9"

services:
  ylerobo:
    build: .
    restart: unless-stopped
    environment:
      YLEROBO_DB: /opt/conf/ylerobo.db
      YLEDL_PARAMS: --destdir /opt/storage
    volumes:
      - "./conf:/opt/conf"
      - "./storage:/opt/storage"
    ports:
      - 8000:8000
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.download.schedule: "@every 60m"
      ofelia.job-exec.download.command: "ylerobo download"
      ofelia.job-exec.download.no-overlap: "true"

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - ylerobo
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

