name: Build and Publish
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    name: Build Docker image and push to repositories
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and publish
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ylerobo
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
